### PR TITLE
Final version of code fixes essential for qtwebkit to work on ppc64le.

### PR DESCRIPTION
**Pull request by asowani**
These are the fixes which are essential for webkit to work without any crash on ppc64le. This has been extensively tested on ppc64le using Ubuntu 16.04 and SLES 12.

### CODE REVIEW

**Comment by asowani** [comment]
@Vitallium Would like to know if there is any chance these fixes will be picked up by you... Thanks!

**Comment by Vitallium** [comment]
@asowani I think I will go ahead and just merge these changes. Since I do not maintain PhantomJS any more.

**Comment by asowani** [comment]
@Vitallium Thank you very much for merging these changes!

**Comment by asowani** [comment]
@Vitallium I observed a strange thing today - I tried to build phantomjs 2.1.1 (git clone, git checkout 2.1.1, git submodule init, then update) and I found that the ppc64le related changes are missing from the qtwebkit. Then I cloned Vitallium/qtwebkit and all these changes are very much present there. So it is strange that PhantomJS is not picking these changes though there are following lines in .gitmodules file:
[submodule "qtwebkit"]
        path = src/qt/qtwebkit
        url = https://github.com/Vitallium/qtwebkit.git
        branch = phantomjs

Any idea what might be going on? Is there any updation that will required by phantomjs?

Thanks,
Atul.

**Pull request merged**
